### ISSUE TITLE
Hide axis labels/ticks

### ISSUE THREAD

**Issue by Paul-James** [timelyportfolio/rcdimple#16]
I'm generating a bar graph that has a lot of bars. The `xAxis` labels are illegible and pointless for my purposes, yet I can't turn them off (I'm using the `addCategoryAxis` type).
Code [here](http://www.buildingwidgets.com/blog/2015/3/18/week-11-dimple-as-htmlwidget) (first graph) shows use of a `hidden` parameter inside the `xAxis()` function, but that parameter actually isn't doing anything (the `ticks = 1` is doing the work).
For a categorical axis, is there a way to hide labels?

**Comment by timelyportfolio** [comment]
Thanks so much for the report.  You are correct.  There is some logic in there for the sort-of-working facets that overrides `hidden` for the primary `x` and `y` axes.  I'll get to work on it.  If an emergency, I can show how to remove these with `tasks`.

**Comment by timelyportfolio** [comment]
@Paul-James, so I believe it is patched up and ready-to-go.  Now `xAxis(hidden=TRUE)` or `yAxis(hidden=TRUE)` will turn it off.

``` r
devtools::install_github("timelyportfolio/rcdimple")
```

**Comment by Paul-James** [comment]
Great! It's not a dire emergency, thank you for working on this and I'll install the branch to test it as well.

**Comment by timelyportfolio** [comment]
I merged into `master` after fairly fully testing it.  @Paul-James, please let me know if you find any problems/bugs.
