### ISSUE TITLE
Possible problem PctAxis

### ISSUE THREAD

**Issue by jpmarindiaz** [timelyportfolio/rcdimple#8]
Hi!
I am running examples 2 and 3 and they give the same result. 
I was expecting to see a normalized (100%) bar stacked bar chart in example 3.
Any hints?

Example 2
![screen shot 2015-04-03 at 8 15 17 pm](https://cloud.githubusercontent.com/assets/1489570/6990910/89d51f6e-da3e-11e4-9c92-daf85869c278.png)

Example 3
![screen shot 2015-04-03 at 8 15 25 pm](https://cloud.githubusercontent.com/assets/1489570/6990909/81a2ca80-da3e-11e4-88d9-16031b1cb61d.png)

**Comment by timelyportfolio** [comment]
Example 3 should be equivalent to the 100% vertical stacked example from dimple.  I'll check into it to see that nothing has changed to disrupt this.  It was working fine earlier.  Does the horizontal stacked 100% also not work?

**Comment by timelyportfolio** [comment]
@jpmarindiaz Thanks so much for finding this error that was introduced in b4a5615f00688c9144e97e54bdbc4a5d3752e6d7 .  Somehow I missed it in my tests.  I believe this should now be resolved in 97a4704cb3bd7f83f947a988c43965c223d9c676.  Please let me know if it still does not work for you.

If you look carefully, you might notice there are two ways now to specify a percent axis, but the preferred and documented way is `type="addPctAxis"`.  For reference, the other way is to do `type="addMeasureAxis", showPercent=T`.

Also, happy you are trying it out.  Would love feedback.

**Comment by jpmarindiaz** [comment]
@timelyportfolio Awesome! Thanks for fixing this so quickly.
Great implementation, I will refactor my package to use yours. Cheers

**Comment by timelyportfolio** [comment]
I think we can close this.  Happy to reopen if not complete.
